### ISSUE TITLE
Numbers change direction

### ISSUE THREAD

**Issue by akudryav** [jayKayEss/Flapper#14]
I use flapper for change number of users online. When it rising it's ok, but when it decreasing, for example from 2 to 1 flapper starts change from 9 to 1. Is it possible to change direction of flapping?

**Comment by jayKayEss** [comment]
Hi @akudryav, I think this would be a little difficult owing to the fixed array of symbols that I'm using.

In addition, the real-life Solari displays could only decrement by looping all the way around the stack—which actually looked pretty cool in real life! I tried to keep Flapper true to the real-life experience.

I understand why folks might want this though, so I'm happy to look at pull requests for it. Just not a priority for me personally.
