### ISSUE TITLE
Performance issues in Chrome and Edge, no issues in Firefox

### ISSUE THREAD

**Issue by NickPapa01** [jayKayEss/Flapper#17]
Hello.

We are using flapper to implement a departures / arrival traffic board in our virtual airline.

I've noticed there are performance issues when using Chrome or Edge compared to Firefox. Flapper seems to be at least 10 times faster in Firefox than Chrome/Edge and it gets worse as displayed data gets increased.

You can see the implementation at https://www.oav.gr/who-is-online

**Comment by NickPapa01** [comment]
Update: Adding the following to the digit class, significantly increased the performance in chrome/edge. It's not as fast as in firefox, but it's acceptable.

-webkit-transform: translatez(0);
-moz-transform: translatez(0);
-ms-transform: translatez(0);
-o-transform: translatez(0);
transform: translatez(0);

**Comment by jayKayEss** [comment]
Thanks, I added this to 1.1.5
